# Setup
title: Likewise Learn
url: https://r3sgame.github.io/likewise-learn-blog/
paginate: 1
baseurl: "/likewise-learn-blog"
permalink: pretty
paginate_path: "/baseurl/page:num/"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: r3sgame
  url: https://twitter.com/r3sgame
  email: r3s.softlocke@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Home
    url: https://likewise-learn.web.app

  - title: Posts
    url: /likewise-learn-blog/archive
